# Financial Data Source Configuration
data_sources:

  # IQFeed Configuration
  iqfeed:
    host: "localhost"
    port: 9100
    username: "${487854}"
    password: "${LTKKma0}"
    real_time: true
    instruments:
      - "SPY"
      - "QQQ"
      - "IWM"
      - "VIX"
      - "TLT"

  # Polygon.io Configuration
  polygon:
    api_key: "${POLYGON_API_KEY}"
    base_url: "https://api.polygon.io"
    rate_limit: 5  # requests per minute
    endpoints:
      stocks: "/v2/aggs/ticker/"
      news: "/v2/reference/news"
      options: "/v3/options/contracts"

  # Quandl Configuration
  quandl:
    api_key: "${QUANDL_API_KEY}"
    base_url: "https://www.quandl.com/api/v3/"
    datasets:
      - "FRED/GDP"
      - "FRED/UNRATE"
      - "TREASURY/YIELD"

  # Yahoo Finance (Free backup)
  yfinance:
    enabled: true
    symbols:
      - "^GSPC"  # S&P 500
      - "^IXIC"  # NASDAQ
      - "^VIX"   # VIX

# Data Processing Configuration
processing:
  alignment:
    frequency: "1min"  # Base frequency for alignment
    market_hours: "09:30-16:00"  # EST
    time_zone: "America/New_York"

  continuous_series:
    window_size: 60  # 60-period rolling window
    std_deviations: 2.0  # ±2 standard deviations
    atr_period: 20
    atr_multiplier: 2.0

  fuzzy_sets:
    membership_functions: "triangular"
    states:
      - "very_low"
      - "low"
      - "medium"
      - "high"
      - "very_high"

  pattern_recognition:
    sequence_length: 7  # Days of context
    confidence_threshold: 0.6