# Symbol-specific bar construction parameters
# Optimized for different symbol characteristics

# High-volume tech stocks
AAPL:
  volume_threshold: 100000      # Volume bars
  dollar_threshold: 10000000    # Dollar bars ($10M)
  imbalance_threshold: 50000    # Imbalance bars
  flow_threshold: 75000         # Flow bars
  volatility_threshold: 0.5     # Volatility bars ($0.50)
  range_size: 0.25              # Range bars ($0.25)
  brick_size: 0.10              # Renko bars ($0.10)

MSFT:
  volume_threshold: 80000
  dollar_threshold: 8000000
  imbalance_threshold: 40000
  flow_threshold: 60000
  volatility_threshold: 0.4
  range_size: 0.20
  brick_size: 0.08

GOOGL:
  volume_threshold: 50000
  dollar_threshold: 15000000    # Higher dollar threshold due to high price
  imbalance_threshold: 25000
  flow_threshold: 40000
  volatility_threshold: 2.0     # Higher due to high price
  range_size: 1.0
  brick_size: 0.50

AMZN:
  volume_threshold: 60000
  dollar_threshold: 12000000
  imbalance_threshold: 30000
  flow_threshold: 45000
  volatility_threshold: 1.5
  range_size: 0.75
  brick_size: 0.40

TSLA:
  volume_threshold: 120000      # Very high volume
  dollar_threshold: 25000000    # Very high volatility
  imbalance_threshold: 60000
  flow_threshold: 90000
  volatility_threshold: 2.0
  range_size: 1.5
  brick_size: 0.75

META:
  volume_threshold: 70000
  dollar_threshold: 15000000
  imbalance_threshold: 35000
  flow_threshold: 50000
  volatility_threshold: 1.0
  range_size: 0.50
  brick_size: 0.25

NVDA:
  volume_threshold: 90000
  dollar_threshold: 20000000    # High volatility
  imbalance_threshold: 45000
  flow_threshold: 70000
  volatility_threshold: 3.0
  range_size: 2.0
  brick_size: 1.0

# ETFs and Indices
SPY:
  volume_threshold: 500000      # Very liquid ETF
  dollar_threshold: 50000000
  imbalance_threshold: 250000
  flow_threshold: 300000
  volatility_threshold: 1.0
  range_size: 0.25
  brick_size: 0.10

QQQ:
  volume_threshold: 300000
  dollar_threshold: 30000000
  imbalance_threshold: 150000
  flow_threshold: 200000
  volatility_threshold: 0.8
  range_size: 0.30
  brick_size: 0.15

IWM:
  volume_threshold: 200000
  dollar_threshold: 20000000
  imbalance_threshold: 100000
  flow_threshold: 120000
  volatility_threshold: 0.6
  range_size: 0.20
  brick_size: 0.08

# Volatility products
VIX:
  volume_threshold: 10000
  dollar_threshold: 1000000     # Lower thresholds for volatility index
  imbalance_threshold: 5000
  flow_threshold: 8000
  volatility_threshold: 2.0
  range_size: 0.50
  brick_size: 0.25

# Default parameters for unlisted symbols
DEFAULT:
  volume_threshold: 50000
  dollar_threshold: 5000000
  imbalance_threshold: 25000
  flow_threshold: 30000
  volatility_threshold: 0.3
  range_size: 0.15
  brick_size: 0.05

# Adaptive scaling factors based on market conditions
MARKET_REGIME_MULTIPLIERS:
  low_volatility:
    volatility_threshold: 0.7   # Reduce thresholds in low vol
    range_size: 0.8
    brick_size: 0.8

  high_volatility:
    volatility_threshold: 1.5   # Increase thresholds in high vol
    range_size: 1.3
    brick_size: 1.3

  low_volume:
    volume_threshold: 0.6       # Reduce volume thresholds
    dollar_threshold: 0.6
    imbalance_threshold: 0.6

  high_volume:
    volume_threshold: 1.4       # Increase volume thresholds
    dollar_threshold: 1.4
    imbalance_threshold: 1.4

# Minimum bar requirements (safety limits)
MIN_TICKS_PER_BAR: 5
MAX_TICKS_PER_BAR: 10000
MIN_BAR_TIMESPAN_SECONDS: 1
MAX_BAR_TIMESPAN_SECONDS: 3600